### ISSUE TITLE
shortcut is overriden by chrome

### ISSUE THREAD

**Issue by avalanche1** [zodern/nice-reload#1]
when pressing ctrl + l on Chrome 45 (windows) it focuses on address bar instead of triggering the package

**Comment by zodern** [comment]
Thanks for reminding me. I will have it use a different shortcut on windows. What do you think of alt+L? Chrome doesn't use it.

**Comment by avalanche1** [comment]
I'm perfectly fine with it :smile:

**Comment by zodern** [comment]
I just released version 2.0.0 with the change.

**Comment by avalanche1** [comment]
:+1:
